### PR TITLE
Fix compilation errors and make the examples work

### PR DESCRIPTION
**Pull request by corebreaker**
Hello,

This PR should resolve compilation errors for ffmpeg v3 and v4 described in #24 , #30 , #32 and #37.
Plus, this PR is based on PR #23 , #25 and #31 .

It has compilation warnings left but, it builds.

### CODE REVIEW

**Comment by PaulWaldo** [comment]
@corebreaker thank you for your work on this!  I forked your repo and did indeed get the examples to complete.  Unfortunately, I cannot get `tutorial01` to pull out the frames.
```
paul-> go run versions.go 
2019/03/08 14:46:43 AvFilter Version:	469093
2019/03/08 14:46:43 AvDevice Version:	3802468
2019/03/08 14:46:43 SWScale Version:	328548
2019/03/08 14:46:43 AvUtil Version:	3675748
2019/03/08 14:46:43 AvCodec Version:	3810148
2019/03/08 14:46:43 Resample Version:	GPL version 3 or later
```
```
paul-> go run tutorial01.go
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 1970-01-01T00:00:00.000000Z
    encoder         : Lavf53.24.2
  Duration: 00:00:05.31, start: 0.000000, bitrate: 1589 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 1205 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 384 kb/s (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : SoundHandler
2019/03/08 14:47:05 Number of Streams:2
2019/03/08 14:47:05 Stream Number: 0
2019/03/08 14:47:05 Stream Number: 1
2019/03/08 14:47:05 Bit Rate: 0
2019/03/08 14:47:05 Channels: 0
2019/03/08 14:47:05 Coded_height: 0
2019/03/08 14:47:05 Coded_width: 0
2019/03/08 14:47:05 Coder_type: 0
2019/03/08 14:47:05 Height: 0
2019/03/08 14:47:05 Profile: 0
2019/03/08 14:47:05 Width: 0
2019/03/08 14:47:05 Codec ID: 0
2019/03/08 14:47:05 Error: Unsupported codec!
```

I'm running on macOS and have `ffmpeg` and `libav` installed via `brew`.  Are you able to run `tutorial01`?

**Comment by corebreaker** [comment]
Hello @PaulWaldo , yes i can build tutorial01, with:
```
2019/03/11 14:51:31 AvFilter Version:   462948
2019/03/11 14:51:31 AvDevice Version:   3801956
2019/03/11 14:51:31 SWScale Version:    328036
2019/03/11 14:51:31 AvUtil Version:     3673700
2019/03/11 14:51:31 AvCodec Version:    3805796
2019/03/11 14:51:31 Resample Version:   GPL version 2 or later
```

I'm under Linux Ubuntu 18.10.
It seems you have a more recent version than me.
With your error message, i suppose that the problem is from ffmpeg.
Sorry concerning ffmpeg, i'm a novice. I just corrected compilation errors on this project. At the beginning, i wanted to concatenate videos.

It'd be better if you'd use Asticode version where the project is maintained. (https://github.com/asticode/go-astiencoder)

**Comment by asticode** [comment]
@corebreaker thanks for pointing to https://github.com/asticode/go-astiencoder ❤️ 

@PaulWaldo problem is the detected codec id is `0` and therefore is invalid. Hence the `Error: Unsupported codec!` error. My guess is that it has to do with the `Streams` function that doesn't return a slice. This specific problem should be fixed using [my fork](https://github.com/asticode/goav), however I'm pretty sure the `tutorial101` will fail elsewhere.

**Comment by PaulWaldo** [comment]
@corebreaker (CC @asticode) I have resolved the error with the @corebreaker PR.  I can now run the tutorial01.go and get frames!  I had to remove calls to deprecated FFmpeg functions and use new ones.  

I want to make a PR to your branch, but am confused on how to do the imports.  Should I use `import "github.com/giorgisio/goav/..."` or change everything to `corebreaker`?  I have a feeling you are now the keeper of the torch 😀

**Comment by asticode** [comment]
If the PR is in this repo, imports should stay `github.com/giorgisio/goav/...`

**Comment by PaulWaldo** [comment]
@corebreaker @asticode I have just created PR https://github.com/giorgisio/goav/pull/42 that should resolve many of the issues people are running into.  The older APIs for which there were bindings just didn't work anymore.  I am able to run the sample program with no problem now.  Hopefully it can get merged in.  Thanks for your help!

**Pull request merged**
