### PR TITLE
Feature/stream codec and codec context

### PR DESCRIPTION
**Pull request by ovr**
Hey! Now I am using own fork and sync pull request for your base repo
1. Implement method `Codec` for `CodecContext`
2. Fixes for Stream getRotation method
3. `Codec` implement methods `getName`, `getLongName`
4. `CodecContext` implement `CodecIsOpen` method instead of `AvcodecIsOpen` (it is needed to be deprecated with unexpected name and not boolean return type)

Thanks

### CODE REVIEW

**Comment by ovr** [comment]
ping @giorgisio

**Comment by ovr** [comment]
ping @giorgisio

**Comment by giorgisio** [comment]
@ovr I haven't done proper tests on the last few merges. I've moved master back to a relatively working version while I go through the recent pull requests, and merges. I will also re-implement Travis CI. (Depends on how much time I get soon). In the mean time, running the examples (cd example && go run tutorial01.go) can point few but critical bugs.

**Comment by ovr** [comment]
@giorgisio 
I cant explain, via In the latest PR i fixes all prevent bugs via I am using fork of goav in production,,,

I fail with  ec3780c and fix it in https://github.com/giorgisio/goav/pull/19

https://github.com/ovr/goav/commit/20263059364d80d37874e5dbdbeedf2063762b4b
image

**Comment by ovr** [comment]
You need to merge it in https://github.com/giorgisio/goav/commits/merged-issues
`merged-issues` and try to run go tutorial
And this will work

**Comment by ovr** [comment]
@giorgisio 
Use this commit https://github.com/ovr/goav/commit/20263059364d80d37874e5dbdbeedf2063762b4b

```
git cherry-pick 20263059364d80d37874e5dbdbeedf2063762b4b
```

in merged-issues branch

**Pull request closed without merging**
