### PR TITLE
[AvFormat] Initial implementation for Dictionary, Stream added GetRot…

### PR DESCRIPTION
**Pull request by ovr**
Hey! Thanks you for this awesome library

I was going to get Stream Rotation to use more perfect/custom scale alghoritm

So, I didnt find anything for it

I've added get `GetRotation` method for Stream aka (struct_AVStream) from ffmpeg
And initial api for `Dictionary (C.struct_AVDictionary)` and `DictionaryEntry (C.struct_AVDictionaryEntry)`

Thanks

### CODE REVIEW

**Comment by Kistamushken** [comment]
:+1:

**Comment by xboston** [comment]
:+1:

**Comment by dedpikhto** [comment]
+

**Comment by AveVlad** [comment]
:+1:

**Comment by AndrewLarin** [comment]
:+1:

**Comment by ovr** [comment]
@giorgisio Thanks for merge
Can you answer on my question from comments

1. When i return struct by pointer and it can be nil (null) I need to return err return variable or it's possible to track by go? Like pointer == nil?

I known that `null` in C language is a defined macros with something like `(void* ) null`
In C++ We can use `nullptr`

Thanks

**Comment by serebro** [comment]
:+1:

**Pull request merged**
