### PR TITLE
Add missing import & include of stream.go

### PR DESCRIPTION
**Pull request by zwh8800**

### CODE REVIEW

**Comment by zwh8800** [comment]
ping @giorgisio

**Comment by ovr** [comment]
I've added fixes in this PR
https://github.com/giorgisio/goav/pull/19

**Comment by ovr** [comment]
https://github.com/ovr/goav/commit/20263059364d80d37874e5dbdbeedf2063762b4b

**Comment by ovr** [comment]
image

But it's not reviewed and merged by @giorgisio

**Pull request merged**
