### PR TITLE
Add missing Avcodec_encode_video2 func.

### PR DESCRIPTION
**Pull request by stephenwithav**
Noticed this was missing.

In issue #1, you wrote that major changes were coming.  Should I avoid future updates like this?

### CODE REVIEW

**Comment by giorgisio** [comment]
This is fine. I've recently freed up sometime to continue working on this. The first batch of changes are related to freeing up memory , and similar issues. 

Thanks, I'm merging your change.

**Comment by stephenwithav** [comment]
Thank you for creating these bindings.

I'm translating the [video encoder example](https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/decoding_encoding.c#L347) from ffmpeg to Go right now.  I'll submit another PR when done.

**Comment by stephenwithav** [comment]
Would you be comfortable with me adding setters to the exported structs?

Something like this: 

```
func (c *AVCodecContext) SetBitrate(rate int) {
        c.bit_rate = (C.int)(rate)
}
```

**Comment by giorgisio** [comment]
The goal of the repo is to expose the C methods to Go. You could probably handle this better on your application.

**Comment by stephenwithav** [comment]
Thank you, giorgisio.

A question, if I may:

```go
package main

import (
	"fmt"

	"github.com/giorgisio/goav/avcodec"
	"github.com/giorgisio/goav/avformat"
)

func main() {
	avformat.Av_register_all()
	mp4Codec := avcodec.Avcodec_find_encoder(13)
	ctx := avcodec.Avcodec_alloc_context3(mp4Codec)
	fmt.Println(ctx.width)
}
```

This sample returns `./testgoav.go:14: ctx.width undefined (cannot refer to unexported field or method width)`.

Is there a way for our apps to modify the `AVCodecContext` settings?  The exposed API doesn't offer any.

**Comment by giorgisio** [comment]
At the moment, avcodec.Width(ctx) is how you can get the width. This is located: avcodec/exported.go I think using AVCodecContext as receivers to expose like width, and similar maybe better on that file.

**Comment by stephenwithav** [comment]
The getters in `exported.go` are a tremendous help.

Setters are needed for encoders, though.  `ctx.width = 640` returns the same error about unexported fields.

**Pull request merged**
